defaults: &defaults
  adapter: mysql2
  encoding: utf8
  pool: 5
  host: 127.0.0.1
  username: root
  password: 

development: &DEV
  <<: *defaults
  database: theyard_development

test: &TEST
  <<: *defaults
  database: theyard_test

production:
  <<: *defaults
  database: theyard_production